import { Products, User, Category } from "@/types/types";


export const data  : {
  users : User[],
  products : Products[],
  categories : Category[]
} = {
  products: [
    {
      _id: "1",
      title: "Estantería de madera",
      price: 15000,
      image: [
        "/images/products/Estanteria.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.5,
      stock: 10,
      description: "Estantería de madera hecha a mano.",
      material: "Roble",    
     userId: "3",
    },
    {
      _id: "2",
      title: "Mesa de café de madera",
      price: 20000,
      image: [
        "/images/products/mesa.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.8,
      stock: 5,
      description: "Mesa de café de madera rústica.",
      material: "Nogal",
     userId: "4",
    },
    {
      _id: "3",
      title: "Cuchara de madera",
      price: 500,
      image: [
        "/images/products/cuchara.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "utensilios",
      rating: 4.2,
      stock: 50,
      description: "Cuchara de madera para cocina.",
      material: "Pino",
     userId: "5",
    },
    {
      _id: "4",
      title: "Tabla de cortar de madera",
      price: 3000,
      image: [
        "/images/products/tabla.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "utensilios",
      rating: 4.7,
      stock: 20,
      description: "Tabla de cortar de madera resistente.",
      material: "Bambú",
     userId: "3",
    },
    {
      _id: "5",
      title: "Puzzle de madera para niños",
      price: 1500,
      image: [
        "/images/products/puzzle.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "juguetes",
      rating: 4.6,
      stock: 30,
      description: "Puzzle de madera educativo para niños.",
      material: "Abedul",
     userId: "4",
    },
    {
      _id: "6",
      title: "Camión de juguete de madera",
      price: 2500,
      image: [
        "/images/products/camion.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "juguetes",
      rating: 4.8,
      stock: 15,
      description: "Camión de juguete hecho de madera.",
      material: "Cedro",
     userId: "3",
    },
    {
      _id: "7",
      title: "Juego de cuchillos de cocina",
      price: 10000,
      image: [
        "/images/products/cuchillos.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "utensilios",
      rating: 4.9,
      stock: 8,
      description: "Juego de cuchillos de cocina con mangos de madera.",
      material: "Roble", 
     userId: "5",
    },
    {
      _id: "8",
      title: "Silla de madera",
      price: 12000,
      image: [
        "/images/products/silla.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.4,
      stock: 12,
      description: "Silla de madera ergonómica.",
      material: "Arce",
     userId: "3",
    },
    {
      _id: "9",
      title: "Caja de almacenamiento de madera",
      price: 5000,
      image: [
        "/images/products/caja.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.3,
      stock: 20,
      description: "Caja de almacenamiento de madera.",
      material: "Pino",
     userId: "6",
    },
    {
      _id: "10",
      title: "Juguete de construcción de madera",
      price: 3500,
      image: [
        "/images/products/construccion.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "juguetes",
      rating: 4.7,
      stock: 25,
      description: "Juego de construcción de madera para niños.",
      material: "Haya",
     userId: "3",
    },
    {
      _id: "11",
      title: "Banco de trabajo de madera",
      price: 18000,
      image: [
        "/images/products/trabajo.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.5,
      stock: 7,
      description: "Banco de trabajo de madera para bricolaje.",
      material: "Fresno",
     userId: "4",
    },
    {
      _id: "12",
      title: "Taburete de madera",
      price: 8000,
      image: [
        "/images/products/taburet.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.6,
      stock: 10,
      description: "Taburete de madera con diseño moderno.",
      material: "Teca",
     userId: "3",
    },
    {
      _id: "13",
      title: "Juego de tazas de madera",
      price: 6000,
      image: [
        "/images/products/tazas.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "utensilios",
      rating: 4.4,
      stock: 20,
      description: "Juego de tazas de madera talladas a mano.",
      material: "Nogal",
     userId: "5",
    },
    {
      _id: "14",
      title: "Bloques de construcción de madera",
      price: 3000,
      image: [
        "/images/products/bloque.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "juguetes",
      rating: 4.7,
      stock: 35,
      description: "Bloques de construcción de madera para niños.",
      material: "Cedro",
     userId: "3",
    },
    {
      _id: "15",
      title: "Lámpara de mesa de madera",
      price: 9000,
      image: [
        "/images/products/lampara.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.8,
      stock: 5,
      description: "Lámpara de mesa con base de madera.",
      material: "Roble",
     userId: "4",
    },
    {
      _id: "16",
      title: "Juego de cucharas medidoras de madera",
      price: 2500,
      image: [
        "/images/products/cucharas.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "utensilios",
      rating: 4.6,
      stock: 20,
      description: "Juego de cucharas medidoras hechas de madera.",
      material: "Pino",
     userId: "3",
    },
    {
      _id: "17",
      title: "Carro de juguete de madera",
      price: 2200,
      image: [
        "/images/products/auto.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "juguetes",
      rating: 4.7,
      stock: 15,
      description: "Carro de juguete de madera para niños.",
      material: "Haya",
     userId: "1",
    },
    {
      _id: "18",
      title: "Cuchillo de chef con mango de madera",
      price: 7000,
      image: [
        "/images/products/carnicero.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "utensilios",
      rating: 4.9,
      stock: 10,
      description: "Cuchillo de chef profesional con mango de madera.",
      material: "Roble",      
     userId: "3",
    },
    {
      _id: "19",
      title: "Mesa plegable de madera",
      price: 15000,
      image: [
        "/images/products/bambu.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "muebles",
      rating: 4.6,
      stock: 8,
      description: "Mesa plegable de madera compacta.",
      material: "Bambú",
     userId: "4",
    },
    {
      _id: "20",
      title: "Set de cubiertos de madera",
      price: 4000,
      image: [
        "/images/products/teca.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "utensilios",
      rating: 4.5,
      stock: 25,
      description: "Set de cubiertos de madera para picnic.",
      material: "Teca",
     userId: "5",
    },
    {
      _id: "21",
      title: "Cartera de cuero artesanal",
      price: 8500,
      image: [
        "/images/products/cartera.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.8,
      stock: 12,
      description: "Cartera de cuero hecha a mano.",
      material: "Cuero",
     userId: "3",
    },
    {
      _id: "22",
      title: "Cinturón de cuero clásico",
      price: 3500,
      image: [
        "/images/products/cinto.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.7,
      stock: 20,
      description: "Cinturón de cuero clásico para hombre.",
      material: "Cuero", 
     userId: "3",
    },
    {
      _id: "23",
      title: "Bolso de mano de cuero",
      price: 12000,
      image: [
        "/images/products/mano.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.9,
      stock: 10,
      description: "Bolso de mano de cuero elegante.",
      material: "Cuero",      
     userId: "5",
    },
    {
      _id: "24",
      title: "Monedero de cuero compacto",
      price: 2000,
      image: [
        "/images/products/billetera.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.6,
      stock: 30,
      description: "Monedero de cuero compacto y duradero.",
      material: "Cuero",
     userId: "1",
    },
    {
      _id: "25",
      title: "Llavero de cuero",
      price: 1000,
      image: [
        "/images/products/llavero.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.5,
      stock: 50,
      description: "Llavero de cuero resistente.",
      material: "Cuero",
     userId: "3",
    },
    {
      _id: "26",
      title: "Funda para laptop de cuero",
      price: 6000,
      image: [
        "/images/products/funda.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.8,
      stock: 15,
      description: "Funda protectora para laptop de cuero.",
      material: "Cuero",
     userId: "8",
    },
    {
      _id: "27",
      title: "Botas de cuero para hombre",
      price: 18000,
      image: [
        "/images/products/bota.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "calzado",
      rating: 4.9,
      stock: 8,
      description: "Botas de cuero resistentes y cómodas.",
      material: "Cuero", 
     userId: "7",
    },
    {
      _id: "28",
      title: "Sandalias de cuero para mujer",
      price: 8000,
      image: [
        "/images/products/chancla.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "calzado",
      rating: 4.7,
      stock: 10,
      description: "Sandalias de cuero elegantes y cómodas.",
      material: "Cuero",
     userId: "6",
    },
    {
      _id: "29",
      title: "Pulsera de cuero trenzado",
      price: 1500,
      image: [
        "/images/products/pulsera.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.6,
      stock: 25,
      description: "Pulsera de cuero trenzado artesanal.",
      material: "Cuero",
     userId: "6",
    },
    {
      _id: "30",
      title: "Funda para cuaderno de cuero",
      price: 4000,
      image: [
        "/images/products/cuaderno.jpg",
        "/images/products/img2.jpg",
        "/images/products/img3.jpg",
        "/images/products/img4.jpg",
      ],
      category: "accesorios",
      rating: 4.8,
      stock: 18,
      description: "Funda protectora para cuaderno hecha de cuero.",
      material: "Cuero",
     userId: "4",
    },
  ],

  users: [
    {
      _id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      password: "password123",
      role: "Seller",
      image: "/images/avatars/hombre.jpg",
      phone: "123-456-7890",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "2",
      name: "Jane Smith",
      email: "alan@gmail.com",
      image: "/images/avatars/hombre.jpg",
      password: "123",
      role: "Customer",
      phone: "123-456-7890",
      address: {
        street: "456 Elm St",
        city: "Los Angeles",
        state: "CA",
        zip: "90001",
      },
      favorites: [],
    },
    {
      _id: "3",
      name: "Admin",
      email: "admin@example.com",
      image: "/images/avatars/mujer.jpg",
      password: "admin123",
      role: "Admin",
      phone: "123-456",
      address: {
        street: "789 Oak St",
        city: "Chicago",
        state: "IL",
        zip: "60601",
      },
      favorites: [],
    },
    {
      _id: "4",
      name: "Carlos Martínez",
      email: "vendedor1@example.com",
      image: "/images/avatars/hombre.jpg",
      password: "password123",
      role: "Seller",
      phone: "123-5465-6546",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "5",
      name: "Ana Rodríguez",
      email: "vendedor2@example.com",
      image: "/images/avatars/mujer.jpg",
      password: "password123",
      phone: "456-1234-547",
      role: "Seller",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "6",
      name: "Javier Gómez",
      email: "vendedor3@example.com",
      password: "password123",
      image: "/images/avatars/hombre.jpg",
      role: "Seller",
      phone: "123-7889-1234",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "7",
      name: "María Fernández",
      email: "vendedor4@example.com",
      image: "/images/avatars/mujer.jpg",
      password: "password123",
      role: "Seller",
      phone: "123-1234-5678",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "8",
      name: "Sofía López",
      email: "vendedor5@example.com",
      password: "password123",
      image: "/images/avatars/mujer.jpg",
      role: "Seller",
      phone: "123-9876-5432",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "9",
      name: "Customer1",
      email: "customer1@example.com",
      password: "password123",
      image: "/images/avatars/mujer.jpg",
      role: "Customer",
      phone: "465-232-4876",
      address: {
        street: "123 Main St",
        city: "Brooklyn",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "10",
      name: "Customer2",
      email: "customer2@example.com",
      password: "password123",
      image: "/images/avatars/hombre.jpg",
      role: "Customer",
      phone: "8987-123-4567",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "11",
      name: "Customer3",
      email: "customer3@example.com",
      password: "password123",
      image: "/images/avatars/hombre.jpg",
      role: "Customer",
      phone: "123-456-7890",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "12",
      name: "Customer4",
      email: "customer4@example.com",
      password: "password123",
      image: "/images/avatars/hombre.jpg",
      role: "Customer",
      phone: "123-456-7890",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    },
    {
      _id: "13",
      name: "Customer5",
      email: "customer5@example.com",
      password: "password123",
      image: "/images/avatars/mujer.jpg",
      role: "Customer",
      phone: "123-456-7890",
      address: {
        street: "123 Main St",
        city: "New York",
        state: "NY",
        zip: "10001",
      },
      favorites: [],
    }
  ],
  categories: [
    {
      _id: "1",
      name: "muebles",
      subCategories: ["sillas", "mesas", "estanterías", "camas", "sofás"],
    },
    {
      _id: "2",
      name: "utensilios",
      subCategories: ["cuchillos", "tablas de cortar", "cucharas", "tazas"],
    },
    {
      _id: "3",
      name: "juguetes",
      subCategories: ["puzzles", "camiones", "bloques de construcción"],
    },
    {
      _id: "4",
      name: "accesorios",
      subCategories: ["carteras", "cinturones", "bolsos", "pulseras"],
    },
    {
      _id: "5",
      name: "calzado",
      subCategories: ["botas", "sandalias", "zapatos"],
    },
  ],
};
